server:
  port: 8080
  servlet:
    context-path: /library

spring:
  application:
    name: Practical Evaluation
  datasource:
    url: jdbc:mysql://localhost:3306/library?createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

security:
  allowed-credentials: true
  allowed-origins:
    - http://localhost:4200 #frontend Url
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - POST
  allowed-headers:
    - Authorization
    - origin
    - Content-type
    - Accept
    - Accept-Control-Allow-Origin
    - Accept-Control-Allow-Header
    - Accept-Control-Request-Method
    - X-Xsrf-Token
  exposed-headers:
    - X-Xsrf-Token

application:
  jwt:
    secretKey: basha12345#123basha12345#123basha12345#123basha12345#123
    tokenPrefix: "Bearer "
    tokenExp: 86400000

